apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obsidian-ingress
  namespace: obsidian
  annotations:
    kubernetes.io/ingress.class: public
spec:
  rules:
  - host: obsidian.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: obsidian-service
            port:
              number: 80
