apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyterlab
spec:
  ingressClassName: nginx
  rules:
    - host: jupyter.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jupyterlab
                port:
                  number: 8888
