apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  labels:
    app: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
        - name: weaviate
          image: semitechnologies/weaviate:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: QUERY_DEFAULTS_LIMIT
              value: "20"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: /var/lib/weaviate
            - name: DEFAULT_VECTORIZER_MODULE
              value: "none"
            - name: ENABLE_MODULES
              value: ""
            - name: CLUSTER_HOSTNAME
              value: weaviate
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 50051
          volumeMounts:
            - name: data
              mountPath: /var/lib/weaviate
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: weaviate-data
